name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbba0a67e6f91a0608fc0807f94b594d0139a8ed11e48914f59fe1995e548ab4"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
